Stemma/Models/UserProfile.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stemma.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserProfileID { get; set; }
        public System.DateTime Birthdate { get; set; }
        public int RelationshipsID { get; set; }
        public int CareerID { get; set; }
        public int CelebrationID { get; set; }
        public int HobbyID { get; set; }
        public int MemoryID { get; set; }
        public int WorldEventID { get; set; }
        public int EventID { get; set; }
    
        public virtual Career Career { get; set; }
        public virtual Celebration Celebration { get; set; }
        public virtual EventTable EventTable { get; set; }
        public virtual HobbyTable HobbyTable { get; set; }
        public virtual Memory Memory { get; set; }
        public virtual Relationship Relationship { get; set; }
        public virtual WorldEvent WorldEvent { get; set; }
    }
}

Stemma/Controllers/UserProfilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stemma.Models;

namespace Stemma.Controllers
{
    public class UserProfilesController : Controller
    {
        private STEMMAEntities db = new STEMMAEntities();

        // GET: UserProfiles
        public ActionResult Index()
        {
            var userProfiles = db.UserProfiles.Include(u => u.Career).Include(u => u.Celebration).Include(u => u.HobbyTable).Include(u => u.Memory).Include(u => u.Relationship).Include(u => u.WorldEvent).Include(u => u.EventTable);
            return View(userProfiles.ToList());
        }

        // GET: UserProfiles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // GET: UserProfiles/Create
        public ActionResult Create()
        {
            ViewBag.CareerID = new SelectList(db.Careers, "CareerID", "CareerID");
            ViewBag.CelebrationID = new SelectList(db.Celebrations, "CelebrationID", "CelebrationID");
            ViewBag.HobbyID = new SelectList(db.HobbyTables, "HobbyID", "HobbyID");
            ViewBag.MemoryID = new SelectList(db.Memories, "MemoryID", "MemoryID");
            ViewBag.RelationshipsID = new SelectList(db.Relationships, "RelationshipsID", "RelationshipsID");
            ViewBag.WorldEventID = new SelectList(db.WorldEvents, "WorldEventID", "WorldEventID");
            ViewBag.EventID = new SelectList(db.EventTables, "EventID", "EventTitle");
            return View();
        }

        // POST: UserProfiles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserProfileID,Birthdate,RegisterUserID,RelationshipsID,CareerID,CelebrationID,HobbyID,MemoryID,WorldEventID,EventID")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userProfile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CareerID = new SelectList(db.Careers, "CareerID", "CareerID", userProfile.CareerID);
            ViewBag.CelebrationID = new SelectList(db.Celebrations, "CelebrationID", "CelebrationID", userProfile.CelebrationID);
            ViewBag.HobbyID = new SelectList(db.HobbyTables, "HobbyID", "HobbyID", userProfile.HobbyID);
            ViewBag.MemoryID = new SelectList(db.Memories, "MemoryID", "MemoryID", userProfile.MemoryID);
            ViewBag.RelationshipsID = new SelectList(db.Relationships, "RelationshipsID", "RelationshipsID", userProfile.RelationshipsID);
            ViewBag.WorldEventID = new SelectList(db.WorldEvents, "WorldEventID", "WorldEventID", userProfile.WorldEventID);
            ViewBag.EventID = new SelectList(db.EventTables, "EventID", "EventTitle", userProfile.EventID);
            return View(userProfile);
        }

        // GET: UserProfiles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            ViewBag.CareerID = new SelectList(db.Careers, "CareerID", "CareerID", userProfile.CareerID);
            ViewBag.CelebrationID = new SelectList(db.Celebrations, "CelebrationID", "CelebrationID", userProfile.CelebrationID);
            ViewBag.HobbyID = new SelectList(db.HobbyTables, "HobbyID", "HobbyID", userProfile.HobbyID);
            ViewBag.MemoryID = new SelectList(db.Memories, "MemoryID", "MemoryID", userProfile.MemoryID);
            ViewBag.RelationshipsID = new SelectList(db.Relationships, "RelationshipsID", "RelationshipsID", userProfile.RelationshipsID);
            ViewBag.WorldEventID = new SelectList(db.WorldEvents, "WorldEventID", "WorldEventID", userProfile.WorldEventID);
            ViewBag.EventID = new SelectList(db.EventTables, "EventID", "EventTitle", userProfile.EventID);
            return View(userProfile);
        }

        // POST: UserProfiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserProfileID,Birthdate,RegisterUserID,RelationshipsID,CareerID,CelebrationID,HobbyID,MemoryID,WorldEventID,EventID")] UserProfile userProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userProfile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CareerID = new SelectList(db.Careers, "CareerID", "CareerID", userProfile.CareerID);
            ViewBag.CelebrationID = new SelectList(db.Celebrations, "CelebrationID", "CelebrationID", userProfile.CelebrationID);
            ViewBag.HobbyID = new SelectList(db.HobbyTables, "HobbyID", "HobbyID", userProfile.HobbyID);
            ViewBag.MemoryID = new SelectList(db.Memories, "MemoryID", "MemoryID", userProfile.MemoryID);
            ViewBag.RelationshipsID = new SelectList(db.Relationships, "RelationshipsID", "RelationshipsID", userProfile.RelationshipsID);
            ViewBag.WorldEventID = new SelectList(db.WorldEvents, "WorldEventID", "WorldEventID", userProfile.WorldEventID);
            ViewBag.EventID = new SelectList(db.EventTables, "EventID", "EventTitle", userProfile.EventID);
            return View(userProfile);
        }

        // GET: UserProfiles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserProfile userProfile = db.UserProfiles.Find(id);
            if (userProfile == null)
            {
                return HttpNotFound();
            }
            return View(userProfile);
        }

        // POST: UserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userProfile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userProfile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Stemma/Views/UserProfiles/Create.cshtml
@model Stemma.Models.UserProfile


@{
    ViewBag.Title = "Create Your Profile";
}

<h2>Create Your Profile</h2>


@using (Html.BeginForm())

{
    @Html.AntiForgeryToken()

    <h4>Complete a simple questionnaire in each of six categories to help build your Stemma.</h4>
        <hr />
        @*<div row="birthdateRow">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="CategoryRow1">
            <div class="col-md-4">
                <div class="box">
                    <div class="icon-wrapper">
                        <i class="fa fa-users fa-4x custom-icon">
                            @*<button onclick="window.location.href='Relationships/Create'"></button>*@
                            <span class="fix-editor">&nbsp;</span>
                        </i>
                    </div>
                    <h4>@Html.ActionLink("Relationships & Family", "Create", "Relationships")</h4>
                    <p>
                        Your friends, loves, children, parents, and others we meet along the way are the people who shape who you are. Who are they, and how did they change you?
                    </p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box">
                    <div class="icon-wrapper">
                        <i class="fa fa-graduation-cap fa-4x custom-icon">
                            <span class="fix-editor">&nbsp;</span>
                        </i>
                    </div>
                    <h4>@Html.ActionLink("Career & Education", "Create", "Careers")</h4>
                    <p>
                        Schools, training, experience, and service define a large part of our lives. Where did you go? What did you see? Who did you meet? What did you learn?
                    </p>
                    </div>
                </div>
            <div class="col-md-4">
                <div class="box">
                    <div class="icon-wrapper">
                        <i class="fa fa-book fa-4x custom-icon">
                            <span class="fix-editor">&nbsp;</span>
                        </i>
                    </div>
                    <h4>@Html.ActionLink("Memories & Stories", "Create", "Memories")</h4>
                    <p>
                        Ancedotes, inside jokes, nicknames, big moves, life changes, advice, life lessons - all the big and little things that make us unique.
                    </p>
                    </div>
                </div>
        </div>
        <div class="CategoryRow2">
                <div class="col-md-4">
                    <div class="box">
                        <div class="icon-wrapper">
                            <i class="fa fa-lightbulb-o fa-5x custom-icon">
                                <span class="fix-editor">&nbsp;</span>
                            </i>
                        </div>
                        <h4>@Html.ActionLink("Hobbies & Interests", "Create", "HobbyTables")</h4>
                        <p>
                            "What do you do?" can mean a lot of different things. What drives you? What do you do when you're not sleeping?
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="box">
                        <div class="icon-wrapper">
                            <i class="fa fa-gift fa-5x custom-icon">
                                <span class="fix-editor">&nbsp;</span>
                            </i>
                        </div>
                        <h4>@Html.ActionLink("Celebrations & Holidays", "Create", "Celebrations")</h4>
                        <p>
                            You're the life of the party - but what do you celebrate, where, when, and how?
                        </p>
                        </div>
                    </div>
                <div class="col-md-4">
                    <div class="box">
                        <div class="icon-wrapper">
                            <i class="fa fa-globe fa-5x custom-icon">
                                <span class="fix-editor">&nbsp;</span>
                            </i>
                        </div>
                        <h4>@Html.ActionLink("Where Were You When...", "Create", "WorldEvents")</h4>
                        <p>
                            You only live once - and you have a unique perspective. How do you remember these event that changed the world, and how did these events change your world?
                        </p>
                        </div>
                    </div>
            </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
            </div>
            @*<div class="form-group">
                    @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Birthdate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RegisterUserID, "RegisterUserID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("RegisterUserID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RegisterUserID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RelationshipsID, "RelationshipsID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("RelationshipsID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.RelationshipsID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CareerID, "CareerID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CareerID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CareerID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CelebrationID, "CelebrationID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("CelebrationID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CelebrationID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HobbyID, "HobbyID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("HobbyID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.HobbyID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MemoryID, "MemoryID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("MemoryID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.MemoryID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.WorldEventID, "WorldEventID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("WorldEventID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.WorldEventID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.EventID, "EventID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("EventID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EventID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>*@
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <link href="~/Content/UserProfileCreate.css" rel="stylesheet" />
    <link href="~/Content/fontawesome/css/font-awesome.min.css" rel="stylesheet" />
}

<div id="navaay" class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Stemma", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            @Html.ActionLink("Timeline", "Index", "EventTables", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @*<li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("FAQ", "Contact", "Home")</li>
                <li>@Html.ActionLink("Get Started", "Contact", "Home")</li>*@
                <li>@Html.ActionLink("Profile", "Create", "UserProfiles")</li>
                <li>@Html.ActionLink("Create Event", "Create", "EventTables")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

Stemma/Views/UserProfiles/Delete.cshtml
@model Stemma.Models.UserProfile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Career.CareerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Career.CareerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celebration.CelebrationID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celebration.CelebrationID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HobbyTable.HobbyID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HobbyTable.HobbyID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Memory.MemoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Memory.MemoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegisterUser.RegisterUserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegisterUser.RegisterUserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Relationship.RelationshipsID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Relationship.RelationshipsID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldEvent.WorldEventID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldEvent.WorldEventID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTable.EventTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTable.EventTitle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Stemma/Views/UserProfiles/Details.cshtml
@model Stemma.Models.UserProfile

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>UserProfile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Birthdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Birthdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Career.CareerID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Career.CareerID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Celebration.CelebrationID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Celebration.CelebrationID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HobbyTable.HobbyID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HobbyTable.HobbyID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Memory.MemoryID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Memory.MemoryID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Relationship.RelationshipsID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Relationship.RelationshipsID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WorldEvent.WorldEventID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WorldEvent.WorldEventID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTable.EventTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTable.EventTitle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.UserProfileID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<div id="navaay" class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Stemma", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            @Html.ActionLink("Timeline", "Index", "EventTables", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("FAQ", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Get Started", "Contact", "Home")</li>*@
                <li>@Html.ActionLink("Profile", "Create", "UserProfiles")</li>
                <li>@Html.ActionLink("Create Event", "Create", "EventTables")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

Stemma/Views/UserProfiles/Index.cshtml
@model IEnumerable<Stemma.Models.UserProfile>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Birthdate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Career.CareerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Celebration.CelebrationID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HobbyTable.HobbyID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Memory.MemoryID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Relationship.RelationshipsID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WorldEvent.WorldEventID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EventTable.EventTitle)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Birthdate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Career.CareerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Celebration.CelebrationID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HobbyTable.HobbyID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Memory.MemoryID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Relationship.RelationshipsID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.WorldEvent.WorldEventID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventTable.EventTitle)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.UserProfileID }) |
            @Html.ActionLink("Details", "Details", new { id=item.UserProfileID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.UserProfileID })
        </td>
    </tr>
}

</table>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Stemma", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            @Html.ActionLink("Timeline", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("FAQ", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Get Started", "Contact", "Home")</li>*@
                <li>@Html.ActionLink("Profile", "Create", "UserProfiles")</li>
                <li>@Html.ActionLink("Create Event", "Create", "EventTables")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("FAQ", "Contact", "Home")</li>
            </ul>

        </div>
    </div>
</div>