Stemma/Controllers/EventTablesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Stemma.Models;

namespace Stemma.Controllers
{
    public class EventTablesController : Controller
    {
        private STEMMAEntities db = new STEMMAEntities();

        // GET: EventTables
        public ActionResult Index()
        {
            //you are trying to add a sorting feature :(


            var queryWholeTimeline = from EventTable in db.EventTables
                                     orderby
                                     //you changed one "descending" to 3 "ascending"
                                       EventTable.EventYear descending,
                                       EventTable.EventMonth descending,
                                       EventTable.EventDay descending
                                     select EventTable;

            //select new
            //{
            //    EventID = EventTable.EventID,
            //    DateCreated = EventTable.DateCreated,
            //    EventTitle = EventTable.EventTitle,
            //    EventDay = EventTable.EventDay,
            //    EventMonth = EventTable.EventMonth,
            //    EventYear = EventTable.EventYear,
            //    PeopleInvolved = EventTable.PeopleInvolved,
            //    EventCaption = EventTable.EventCaption
            //};

            //try this instead:
            //select EventTable;
            //apparently, nope.

            //foreach (var timePoint in queryWholeTimeline)
            //{
            //something
            //}

            //this was the only original line in this code:
            //return View(db.EventTables.ToList());

            //try changing it to:
            //return View(queryWholeTimeline.ToList());
            return View(queryWholeTimeline);
            //or not lol


        }

        // GET: EventTables/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventTable eventTable = db.EventTables.Find(id);
            if (eventTable == null)
            {
                return HttpNotFound();
            }
            return View(eventTable);
        }

        // GET: EventTables/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EventTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EventID,DateCreated,EventTitle,EventDay,EventMonth,EventYear,PeopleInvolved,EventCaption,UploadMedia")] EventTable eventTable)
        {
            if (ModelState.IsValid)
            {
                db.EventTables.Add(eventTable);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(eventTable);
        }

        // GET: EventTables/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventTable eventTable = db.EventTables.Find(id);
            if (eventTable == null)
            {
                return HttpNotFound();
            }
            return View(eventTable);
        }

        // POST: EventTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EventID,DateCreated,EventTitle,EventDay,EventMonth,EventYear,PeopleInvolved,EventCaption,UploadMedia")] EventTable eventTable)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventTable).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(eventTable);
        }

        // GET: EventTables/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventTable eventTable = db.EventTables.Find(id);
            if (eventTable == null)
            {
                return HttpNotFound();
            }
            return View(eventTable);
        }

        // POST: EventTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventTable eventTable = db.EventTables.Find(id);
            db.EventTables.Remove(eventTable);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Stemma/Views/EventTables/Delete.cshtml
@model Stemma.Models.EventTable

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EventTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeopleInvolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeopleInvolved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventCaption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventCaption)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UploadMedia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadMedia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Stemma/Views/EventTables/Details.cshtml
@model Stemma.Models.EventTable

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EventTable</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventMonth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventMonth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeopleInvolved)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeopleInvolved)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EventCaption)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EventCaption)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.UploadMedia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UploadMedia)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EventID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<div id="navaay"class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Stemma", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            @Html.ActionLink("Timeline", "Index", "EventTables", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("FAQ", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Get Started", "Contact", "Home")</li>*@
                <li>@Html.ActionLink("Profile", "Create", "UserProfiles")</li>
                <li>@Html.ActionLink("Create Event", "Create", "EventTables")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

Stemma/Views/EventTables/Edit.cshtml
@model Stemma.Models.EventTable

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>EventTable</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EventID)

    <div class="form-group">
        @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventTitle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventTitle, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventTitle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventDay, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventDay, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventDay, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventMonth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventMonth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventMonth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventYear, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventYear, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventYear, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PeopleInvolved, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PeopleInvolved, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PeopleInvolved, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventCaption, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EventCaption, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EventCaption, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UploadMedia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UploadMedia, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UploadMedia, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Stemma/Views/EventTables/Index.cshtml
@model IEnumerable<Stemma.Models.EventTable>

@{
    ViewBag.Title = "Your TimeLine";
}
<script src="https://static.filestackapi.com/v3/filestack.js"></script>
<script src="~/Scripts/fileUploader.js"></script>
<link href="~/Content/TimeLine.css" rel="stylesheet" />
<h2>Your Stemma Timeline</h2>

<section class="timeline">
    <ul>
        @foreach (var item in Model)
        {

            <li>
                <div>
                    <h1><b>@Html.DisplayFor(modelItem => item.EventTitle)</b></h1>


                    <img class="uploadedImage" src="@item.UploadMedia" alt="DanaPic" id="itemImg" />                  


                    <time>@Html.DisplayFor(modelItem => item.EventYear)</time>
                    <p>@Html.DisplayFor(modelItem => item.EventCaption)</p>




                    @*@Html.ActionLink("Edit", "Edit", new { id = item.EventID }) |*@
                    @*@Html.ActionLink("Details", "Details", new { id = item.EventID }) |*@
                    @*@Html.ActionLink("Delete", "Delete", new { id = item.EventID })*@
                </div>
            </li>
        }



    </ul>
</section>


@*@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreated)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventDay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventMonth)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PeopleInvolved)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EventCaption)
        </td>*@
        @*<td>
            @Html.ActionLink("Edit", "Edit", new { id=item.EventID }) |
            @Html.ActionLink("Details", "Details", new { id=item.EventID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.EventID })
        </td>
    </tr>
}*@

@*</table>*@
<div id="navaay"class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @*@Html.ActionLink("Stemma", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            @Html.ActionLink("Your Timeline", "Index", "EventTables", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @*<li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("FAQ", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Get Started", "Contact", "Home")</li>*@
                <li>@Html.ActionLink("Your Profile", "Create", "UserProfiles")</li>
                <li>@Html.ActionLink("Create Event", "Create", "EventTables")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>